### ISSUE TITLE
Hello, I have a question to ask you

### ISSUE THREAD

**Issue by Guangwen11** [Ultrawipf/OpenFFBoard-configurator#6]
Hello, I use QTC+ + to write an upper computer can communicate, but only received OK data, not other data, I open the serial port directly on the communication, also need to carry out other operations?
Thank you very much!

**Comment by Ultrawipf** [comment]
What do you send? If you send a message like "power=10;" you will get an OK back. if you request the value as "power?;" then you will get the current value.

You can also ask questions in the discord. Is maybe easier.

**Comment by Guangwen11** [comment]
Oh!I am the message that wrote "power=10".So I say "Power?;"Can I get its value?

**Comment by Guangwen11** [comment]
Hello!I tried your method but I accepted the mistake &gt;Err(0). Unknown command: Power?Power\n"

**Comment by Guangwen11** [comment]
Hello, is the request value sent?I sent the "power?", still not read the data..
Thanks for answering ！！！！
