### ISSUE TITLE
Hello, a question to consult the small white

### ISSUE THREAD

**Issue by Guangwen11** [Ultrawipf/OpenFFBoard-configurator#8]
Hello, I sent "Power?"Still no data read, do you need to shake hands or other communication after opening the serial port?Little white one, can you tell me in detail?Thank you very much!

**Comment by Ultrawipf** [comment]
You have to read data with "<cmd>?;". Terminate a command with ";" or a newline and set values with "<cmd>=<value>;" You can send "help" for some examples as well.
Please do not open new issues for the same questions and contact me via discord instead if you need more help.
