### ISSUE TITLE
Translation is loaded after MainWindow.ui loaded, making UI partial translated.

### ISSUE THREAD

**Issue by tinyboxxx** [Ultrawipf/OpenFFBoard-configurator#85]
This is only happened when start GUI, changing language from menu dropdown is working normally.

![image](https://github.com/user-attachments/assets/2784ee4f-4d67-4264-9640-04ee6b6d242b)

I added some print for debug:
```
PS C:\Users\tinybox\Documents\GitHub\OpenFFBoard-configurator> & C:/Users/tinybox/AppData/Local/Programs/Python/Python312/python.exe c:/Users/tinybox/Documents/GitHub/OpenFFBoard-configurator/main.py
UI file loaded : MainWindow.ui
UI file loaded : profile.ui
UI file loaded : profile_list.ui
Language file loaded: translations\zh_CN.qm
UI file loaded : errors.ui
UI file loaded : effects_stats.ui
UI file loaded : effects_graph.ui
UI file loaded : activelist.ui
UI file loaded : activelist.ui
UI file loaded : serialchooser.ui
UI file loaded : statusbar.ui
UI file loaded : ffbclass.ui
UI file loaded : effects_tuning.ui
UI file loaded : axis_ui.ui
UI file loaded : encoder_tune.ui
UI file loaded : tmc4671_ui.ui

```

**Comment by Ultrawipf** [comment]
Thanks for the details, i will check if there is any way to load the translation before the main UI easily. 
If not it might require some restructuring of the startup code as it is currently loaded within the main window class.

It seems like it should trigger a full app restart if the language is different but might not reload the main UI properly.
